---
#title: "Projeto I"
#author:
#date: "`r Sys.Date()`"
output:
  bookdown::html_document2:
    new_session: true
    number_sections: false
    fig_caption: true
#header-includes: \usepackage[brazil]{babel}
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
	echo = FALSE, # true mostra o codigo
	message = FALSE,
	warning = FALSE
)
#options(OutDec = ",")
```

```{r pacotes, message=FALSE, warning=FALSE}
library(tidyverse)
library(readxl) 
library(patchwork) # para parcionar os graficos
library(janitor)
library(kableExtra)
# rode uma vez soh
```

```{r limpa_env}
rm(list = ls())

df1 <- read_xlsx("dados.xlsx", sheet = "Dados Atuais")
df2 <- read_xlsx("dados.xlsx", sheet = "Dados Gestacionais")
df3 <- read_xlsx("dados.xlsx", sheet = "ELISAs")
df4 <- read_xlsx("dados.xlsx", sheet = "Imunoturbidimetria")
df5 <- read_xlsx("dados.xlsx", sheet = "Doenças Crônicas")
df6 <- read_xlsx("dados.xlsx", sheet = "Aspectos Psicológicos")
```

```{r funcoes_trata_dados}
##Funções para tratar os dados:

coluna_na_numerica <- function(lista, caracter = ".", substituto = ""){
  lista %>% 
    str_replace(. , pattern = ",", replacement = ".") %>%
    str_replace_na(. , replacement = "") %>% 
    ifelse(. == caracter, substituto, .) %>% as.numeric()
}

coluna_numerica <- function(lista){
  lista %>% 
    ifelse(. == 99999, NA, .) %>% as.numeric()
}
```

```{r tratamento_df1}
#### DF1: Dados Atuais

colunas_interesse <- c(
  "NOME    (iniciais)",
  "GRUPO      MN:0      MP:1",
  "ETNIA                1:branca   2:parda   3:negra",
  "IDADE    anos",
  "ESCOLARIDADE COMPLETA  0: 4ª série completa   1:fundamental completo 2:médio completo 3:ensino técnico completo 4:superior completo 5:pós-graduação completa",
  "DOENÇA CRÔNICA  0:não   1:hipertensão   2:diabetes   3:hipercolesterolemia   4:fibromialgia   5:glaucoma   6:enxaqueca   7:hipotireoidismo   8:asma   9:esteatose hepática   10:síndrome do intestino irritável   11:hemangioma   12:trombofilia   13:bronquite   14:rinite   15:ovário policístico   16:TAG   17:sinusite   18:depressão   19: artrose   20:leucocitose   21:anemia   22:síndrome do pânico   23:gastrite   24:hepatite   25:crise alérgica   26:cistite  27:anemia falciforme   28:mioma uterino   29:cálculo renal   30:calcificação mamária   31:hipoglicemia   32:derrame de vista   33:hidradenite  34:glomeruloesclerose 35:pré-diabetes 36:bipolaridade 37:TDAH 38:TEA 39:Doença de Still",
  "NÚMERO GESTAÇÕES",
  "Grupo sanguíneo ABO         0:A         1:B         2:O          3: AB",
  "RH   0:negativo   1:positivo",
  "Peso (kg)",
  "Altura (m)",
  "IMC",
  "GORDURA (%)",
  "PRESSÃO SISTÓLICA (mmHg)",
  "PRESSÃO DIASTÓLICA (mmHg)",
  "PRESSÃO ARTERIAL MÉDIA",
  "CINTURA (cm)",
  "ABDÔMEN (cm)",
  "QUADRIL (cm)",
  "RELAÇÃO CINTURA/QUADRIL",
  "RBC (106/µL)",
  "HGB (g/dL)",
  "HCT (%)",
  "VCM (µm³)",
  "HCM (pg)",
  "CHCM (g/dL)",
  "RDW-CV (%)",
  "RDW-SD (µm³)",
  "PLT (10³/µL)",
  "PCT (%)",
  "VPM (µm³)",
  "PDW (µm³)",
  "P-LCC (10³/µL)",
  "P-LCR (%)",
  "WBC (10³/µL)",
  "NEU (10³/µL)",
  "LYM (10³/µL)",
  "MON (10³/µL)",
  "EOS (10³/µL)",
  "BASO (10³/µL)",
  "LIC (10³/µL)",
  "NLR",
  "Colesterol total (mg/dL)",
  "HDL (mg/dL)",
  "LDL (mg/dL) DOSADO",
  "VLDL (mg/dL)",
  "Não-HDL (mg/dL)",
  "Triglicérides (mg/dL)",
  "HbA1c (%)",
  "Creatinina (mg/dL)",
  "Ritmo de filtrção glomerular calculado",
  "TGP/ALT",
  "TGO/AST",
  "Ácido Úrico",
  "CK",
  "Gama GT",
  "USA ANTI-HIPERTENSIVO 0:não 1:sim",
  "USA MEDICAMENTO PARA DIABETES 0:não 1:sim",
  "USA MEDICAMENTO PARA HIPERCOLESTEROLEMIA 0:não 1:sim",
  "TABAGISTA 0: não   1:sim", 
  "ETILISTA    0: não   1:sim",
  "Glicemia capilar (mg/dL)",
  "Glicose"
  )

renomear_colunas <- c(
  "iniciais",
  "grupo",
  "etnia",
  "idade",
  "escolaridade",
  "doenca",
  "num_gestacoes",
  "gpsanguineo",
  "rh",
  "peso",
  "altura",
  "imc",
  "gordura",  
  "pressao_sis",
  "pressao_dias",
  "pressao_media", 
  "cintura",
  "abdomen",
  "quadril",
  "cintura_quadril",
  "rbc",
  "hgb",
  "hct",
  "vcm",
  "hcm",
  "chcm",
  "rdwcv",
  "rdwsd",
  "plt",
  "pct",
  "vpm",
  "pdw",
  "plcc",
  "plcr",
  "wbc",
  "neu",
  "lym",
  "mon", 
  "eos",
  "baso",
  "lic",
  "nlr",
  "colesterol_total",
  "hdl",
  "ldl_dosado",
  "vldl",
  "nao_hdl",
  "triglicerides",
  "hba1c",
  "creatinina",
  "filtr_glomerular",
  "tgp_alt",
  "tgo_ast",
  "acido_urico",
  "ck",
  "gama_gt",
  "anti_hiper",
  "medic_diabetes",
  "medic_hipercol",
  "tabagista",
  "elitista",
  "glicemia",
  "glicose"
  )

df1 <- df1 %>% dplyr::select(all_of(colunas_interesse))
colnames(df1) <- renomear_colunas

grupos_nulos <- df1 %>% dplyr::select(grupo) %>% is.na()
df1 <- df1 %>% 
  filter(!grupos_nulos) %>% 
  mutate(
    grupo = as.factor(grupo),
    etnia = coluna_numerica(etnia),
    escolaridade = as.factor(escolaridade),
    doenca = gsub("\\.", ",", doenca),
    gpsanguineo = coluna_numerica(gpsanguineo),
    rh = coluna_numerica(rh),
    peso = coluna_numerica(peso),
    altura = coluna_numerica(altura),
    imc = coluna_na_numerica(imc, "#DIV/0!", NA) %>% coluna_numerica() %>% round(2),
    gordura = coluna_na_numerica(gordura) %>% coluna_numerica(),
    pressao_sis = coluna_numerica(pressao_sis),
    pressao_dias = coluna_numerica(pressao_dias),
    pressao_media = coluna_numerica(pressao_media) %>% round(2),
    cintura = coluna_numerica(cintura),
    abdomen = coluna_numerica(abdomen),
    quadril = coluna_numerica(quadril),
    cintura_quadril = coluna_na_numerica(cintura_quadril, "#DIV/0!", NA) %>% coluna_numerica() %>% round(2),
    mon = coluna_numerica(mon),
    nlr = coluna_na_numerica(nlr, "#DIV/0!", NA) %>% coluna_numerica(),
    ldl_dosado = coluna_na_numerica(ldl_dosado, "#DIV/0!", NA) %>% coluna_numerica(),
    vldl = coluna_na_numerica(vldl, "#DIV/0!", NA) %>% coluna_numerica() %>% round(2),
    nao_hdl = coluna_numerica(nao_hdl) %>% round(2),
    hba1c = coluna_numerica(hba1c) %>% round(2),
    creatinina = coluna_numerica(creatinina),
    filtr_glomerular = coluna_na_numerica(filtr_glomerular, "#DIV/0!", NA) %>% coluna_numerica(),
    ck = coluna_numerica(ck),
    glicemia = coluna_numerica(glicemia),
    glicose = coluna_numerica(glicose)
    )

df1 <- df1 %>%
  mutate_at(vars(-c(iniciais, grupo, escolaridade, doenca, etnia, num_gestacoes)), as.numeric)%>%
  mutate(sangueo = ifelse(gpsanguineo == 2, 1, 0),
         razaoldl = ldl_dosado/colesterol_total,
         num_gestacoes = ifelse(num_gestacoes == 1, 1, ifelse(num_gestacoes == 2, 2, 3))
         )
```

```{r tratamento_df2}
####  DF2: Dados Gestacionais

colunas_interesse <- c(
  "NOME    (iniciais)",
  "GRUPO      MN:0      MP:1",
  "Ano",
  "Há quantos anos",
  "PARTO                                     0:normal   1:cesariana   2:fórceps",
  "PESO BEBÊ (kg)",
  "SEXO BEBÊ 0:feminino   1:masculino",
  "MESMO PAI 0:não        1:sim      2:não se aplica (primigesta)",
  "INTERVALO ENTRE PARTOS (meses) 0:primigesta",
  "PARTO PREMATURO 0:não      1:sim",
  "GESTAÇÃO MÚLTIPLA  (gêmeos) 0:não   1:sim"
  )

renomear_colunas <- c(
  "iniciais",
  "grupo",
  "ano",
  "quantos_anos_evento",
  "tipo_parto",
  "peso_bebe",
  "sexo_bebe",
  "mesmo_pai",
  "intervalo_partos",
  "prematuro",
  "gemeos"
  )

df2 <- df2 %>% dplyr::select(all_of(colunas_interesse))
colnames(df2) <- renomear_colunas

grupos_nulos <- df2 %>% dplyr::select(grupo) %>% is.na()
df2 <- df2 %>% 
  filter(! grupos_nulos) %>% 
  mutate(
    grupo = as.factor(grupo),
    quantos_anos_evento = quantos_anos_evento %>% as.numeric(),
    peso_bebe = coluna_numerica(peso_bebe),
    tipo_parto = as.factor(coluna_numerica(tipo_parto)),
    prematuro = as.factor(prematuro)
    )
```

```{r tratamento_df3}
#### DF3: ELISAs

colunas_interesse <- c(
  "NOME    (iniciais)",
 "GRUPO      MN:0      MP:1", 
 "PAI-1 (ng/mL)",
 "Log PAI-1 (ng/mL)",
 "TROMBOMODULINA (ng/mL)",
 "ADMA (ng/mL)",
 "sFlt1 (pg/mL)",
 "Absorbâncias sFlt1",
 "AA-AT1 (ng/mL)"
)

renomear_colunas <- c(
  "iniciais",
 "grupo", 
 "pai1",
 "logpai1",
 "trombomodulina",
 "adma",
 "sflt1",
 "absor_sflt1",
 "aaat1"
)
df3 <- df3 %>% dplyr::select(all_of(colunas_interesse))

colnames(df3) <- renomear_colunas

df3 <- df3 %>% drop_na(grupo) %>% 
  mutate(
  pai1 = coluna_numerica(pai1) %>% round(2),
  logpai1 = coluna_numerica(logpai1) %>% round(2),
  trombomodulina = coluna_numerica(trombomodulina),
  adma = coluna_numerica(adma), 
  sflt1 = coluna_na_numerica(sflt1, "< curva", NA) %>% coluna_numerica() %>% round(2),
  absor_sflt1 = coluna_numerica(absor_sflt1) %>% round(2),
  aaat1 = coluna_numerica(aaat1) %>% round(2)
)

df3 <- df3 %>%
  mutate_at(vars(-iniciais), as.numeric)

# corrigindo outro erro de adma
df3$adma <- df3$adma %>% ifelse(. == 999999, NA, .) %>% as.numeric()
```

```{r tratamento_df4}
#### DF4: Imunoturbidimetria

colunas_interesse <- c(
   "NOME    (iniciais)",
 "GRUPO      MN:0      MP:1", 
 "DÍMERO-D (ng/mL)",
 "LOG DÍMERO-D"
)
renomear_colunas <- c(
  "iniciais",
 "grupo", 
 "dimero",
 "logdimero"
)
df4 <- df4 %>% dplyr::select(all_of(colunas_interesse))
colnames(df4) <- renomear_colunas

df4 <- df4 %>% 
  mutate_at(vars(-iniciais), as.numeric)

# alterando df4
df4 <- df4 %>% mutate(
    dimero = coluna_numerica(dimero),
    logdimero = coluna_numerica(logdimero) %>% round(2)
)
```

```{r tratamento_df5}
#### DF5: Doenças Crônicas

colunas_interesse <- c(
  "NOME    (iniciais)",
 "GRUPO      MN:0      MP:1", 
 "HIPERTENSÃO 0:não   1:sim",
 "DIABETES 0:não   1:sim",
 "HIPERCOLESTEROLEMIA 0:não   1:sim",
 "FIBROMIALGIA 0:não   1:sim",
 "GLAUCOMA 0:não   1:sim",
 "ENXAQUECA 0:não   1:sim",
 "HIPOTIREOIDISMO 0:não   1:sim",
 "ASMA 0:não   1:sim",
 "ESTEATOSE HEPÁTICA 0:não   1:sim",
 "SÍNDROME DO INTESTINO IRRITÁVEL 0:não   1:sim",
 "HEMANGIOMA  0:não   1:sim",
 "TROMBOFILIA  0:não   1:sim",
 "BRONQUITE  0:não   1:sim",
 "RINITE  0:não   1:sim",
 "OVÁRIOS POLICÍSTICOS 0:não   1:sim",
  "Transtorno de ansiedade generalizada (TAG)  0:não   1:sim",
 "SINUSITE 0:não 1:sim",
 "DEPRESSÃO 0:não   1:sim",
 "ARTROSE 0:não   1:sim",
 "LEUCOCITOSE 0:não   1:sim",
 "ANEMIA 0:não   1:sim",
 "SÍNDROME DO PÂNICO 0:não   1:sim",
 "GASTRITE 0:não   1:sim",
 "HEPATITE 0:não   1:sim",
 "CRISE ALÉRGICA 0:não   1:sim",
 "CISTITE 0:não   1:sim",
 "ANEMIA FALCIFORME 0: não 1:sim",
 "MIOMA UTERINO 0: não 1: sim",
 "CÁLCULO RENAL 0: não 1: sim",
 "CALCIFICAÇÃO MAMÁRIA 0: não 1: sim",
 "HIPOGLICEMIA 0: não 1: sim",
 "DERRAME DE VISTA 0: não 1: sim",
 "HIDRADENITE 0: não 1: sim",
 "GLOMERULOESCLEREOSE  0: não 1: sim",
 "PRÉ-DIABETES 0: não 1: sim",
  "BIPOLAR 0: não 1: sim",
  "TDAH 0: não 1: sim",
  "TEA 0: não 1: sim",
  "DOENÇA DE STILL 0: não 1: sim"
)

renomear_colunas <- c(
  "iniciais",
 "grupo", 
 "hipertensao",
 "diabetes",
 "hipercolesterolemia",
 "fibromialgia",
 "glaucoma",
 "enxaqueca",
 "hipotireoidismo",
 "asma",
 "esteatose_hepatica",
 "sindrome_intestino_irritavel",
 "hemangioma",
 "trombofilia",
 "bronquite",
 "rinite",
 "ovario_policistico",
 "tag",
 "sinusite",
 "depressao",
 "artrose",
 "leucocitose",
 "anemia",
 "sindrome_panico",
 "gastrite",
 "hepatite",
 "crise_alergica",
 "cistite",
 "anemia_falciforme",
 "mioma_uterino",
 "calculo_renal",
 "calcificacao_mamaria",
 "hipoglicemia",
 "derrame de vista",
 "hidradenite",
 "glomeruloesclerose",
 "pre_diabetes",
 "bipolaridade",
 "tdah",
 "tea",
 "still"
)

df5 <- df5 %>% dplyr::select(all_of(colunas_interesse))
colnames(df5) <- renomear_colunas

df5 <- df5 %>% 
  mutate_at(vars(-iniciais), as.numeric)
```

```{r tratamento_df6}
names(df6)[10] <- 'FILHOS VIVOS NO PERÍODO DA GESTAÇÃO: 0:sem filhos 1: um filho 2: dois ou mais filhos'

#### DF6: Aspectos Psicologicos

colunas_interesse <- c(
  "NOME    (iniciais)",
 "GRUPO      MN:0      MP:1", 
 "REDE DE APOIO             0:não   1:sim",                                                                          
 "PRIMEIRO FILHO     0:não   1:sim",
 "FILHOS VIVOS NO PERÍODO DA GESTAÇÃO: 0:sem filhos 1: um filho 2: dois ou mais filhos",
 "TRABALHAVA FORA       0:não       1:sim",                                                                          
 "RELACIONAMENTO COM O PAI                                  0:não tinha     1:ruim   2:normal   3:bom   4:excelente",
 "APOIO DO PARCEIRO            1:nenhum                 2:pouco                         3:muito"                    
 )

renomear_colunas <- c(
  "iniciais",
 "grupo", 
 "apoio",
 "1o_filho",
 "filhos_vivos",
 "trabalha",
 "relac_pai",
 "apoio_pai"
)

df6 <- df6 %>% dplyr::select(all_of(colunas_interesse))

colnames(df6) <- renomear_colunas

df6 <- df6 %>% drop_na(grupo) %>% 
  mutate(
    filhos_vivos = coluna_numerica(filhos_vivos),
  relac_pai = coluna_numerica(relac_pai),
)

df6 <- df6 %>%
  mutate_at(vars(-c(iniciais)), as.numeric)
```

```{r resumo_df}
df1 <- df1 %>% mutate(grupo = as.factor(grupo))
df2 <- df2 %>% mutate(grupo = as.factor(grupo))
df3 <- df3 %>% mutate(grupo = as.factor(grupo))
df5 <- df5 %>% mutate(grupo = as.factor(grupo))

df_completo <- left_join(df1 %>% select(-ck),
                         df2 %>% select(iniciais, grupo, quantos_anos_evento),
                         df3 %>% select(iniciais, grupo, trombomodulina, adma),
                         by = join_by(iniciais, grupo), relationship = "many-to-many") %>%
               left_join(., 
                         df5 %>% select(iniciais,grupo,hipertensao,diabetes,hipercolesterolemia),
                         by = join_by(iniciais, grupo), relationship = "many-to-many") %>% 
  select(- iniciais)

cols <- df_completo %>% names()
cat <- c("grupo", "etnia", "escolaridade", "doenca", "num_gestacoes", "gpsanguineo",
         "rh", "medic_diabetes", "medic_hipercol", "tabagista", "elitista", "anti_hiper",
         "hipertensao", "diabetes", "hipercolesterolemia")
num <- c("grupo", cols[! cols %in% cat])

df_num <- df_completo %>% select(all_of(num))
df_cat <- df_completo %>% select(all_of(cat))
df_cat <- df_cat %>%
  mutate(categoriaimc = case_when(
    df_num$imc <= 24.99 ~ "magraza/eutrofia",
    df_num$imc <= 29.99 ~ "sobrepeso",
    TRUE ~ "obesidade"
  ))

# Novas categorias nas variaveis
df_num <- df_num %>% mutate(ldl_colesterol = ldl_dosado/colesterol_total) 

df_cat <- df_cat %>% mutate(
  escolaridade_bin = ifelse(escolaridade %in% c(3, 4), "superior", "basico"))
```


```{r tema_graficos}
cor_verde = c("#4fb6a7")
cor_roxa = c("#652177")

cores = colorRampPalette(c("#4fb6a7","#652177"))
tema = theme_minimal() + 
       theme(axis.title.y = element_text(angle = 90, margin = unit(c(0.3, 0.5, 0.3, 0), "cm")),
             axis.title.x = element_text(margin = unit(c(0.3, 0, 0, 0), "cm")),
             axis.line.x = element_line(linewidth = 0.6, linetype=1),
             axis.line.y = element_line(linewidth = 0.6, linetype=1),
             axis.ticks.y = element_line(linewidth = 0.6, linetype = 1),
             axis.text = element_text(size=10),
             legend.position = "right",
             plot.margin = unit(c(0.3, 0.4, 0.3, 0.4), "cm"),
             plot.subtitle = element_text(hjust = 0.5, vjust= 4))
theme_set(tema)
```

## Resumo testes de hipóteses

### Dados numéricos

Para os dados numéricos, os testes tiveram por hipótese geral:

```{=tex}
\begin{eqnarray}
        {
        \left\{\begin{array}{lcc}
        H_{0}: {\theta_{Grupo~MN} = \theta_{Grupo~MP}} \\
        H_{1}: {\theta_{Grupo~MN} \neq \theta_{Grupo~MP}}
        \end{array}\right.
        }    \nonumber
    \end{eqnarray}
```


```{r funcao_teste_hipotese}
realizar_teste <- function(dataframe, variavel) {
  
  dataframefiltrado <- dataframe %>% drop_na(grupo) %>% mutate(grupo = ifelse(grupo == "0", "MN", "MP")) 
  grupo_MN<- dataframefiltrado %>% filter(grupo == "MN") %>% pull(variavel)
  grupo_MP<- dataframefiltrado %>% filter(grupo == "MP") %>% pull(variavel)

  tabela <- dataframefiltrado %>% group_by(grupo) %>%
    summarise(
      N = sum(!is.na( !!sym(variavel) )),
      Nulo =  sum( is.na( !!sym(variavel) )),
      `Média` = mean( !!sym(variavel) , na.rm = T),
      "DesPad" = sd( !!sym(variavel) , na.rm = T),
      "Min" = min( !!sym(variavel) , na.rm = T),
      "Q1" = quantile( !!sym(variavel) , na.rm = T, .25)[[1]],
      "Mediana" = quantile( !!sym(variavel) , na.rm = T, .5)[[1]],
      "Q3" = quantile( !!sym(variavel) , na.rm = T, .75)[[1]],
      "Máx" = max( !!sym(variavel) , na.rm = T),
      `P(Norm)` = shapiro.test( !!sym(variavel) )$p.value,
      `P(Test-T)` = t.test(grupo_MN, grupo_MP, alternative = "two.sided")$p.value,
      `P(Manh-W)` = wilcox.test(grupo_MN, grupo_MP, correct = FALSE,  alternative = "two.sided")$p.value,
      `Variável` = variavel
    )
  
  tabela <- tabela %>% select(`Variável`, everything())
  return(tabela)
}
```


```{r aplicando_teste_numericos}
### Idade:
variavel <- "idade"
teste <- realizar_teste(df_num, variavel)
tabela_resumo <- teste

todas_variaveis <- names(df_num)[-c(1,2)]
for(variavel in todas_variaveis){
  teste <- realizar_teste(df_num, variavel)
  tabela_resumo <- rbind(tabela_resumo, teste)
}

kbl(
  tabela_resumo %>% arrange(`P(Manh-W)`), 
  digits = 3,
  format.args = list(decimal.mark = ',', big.mark = ".") 
  ) %>%
  kable_paper(full_width = F) %>%
  column_spec(1, bold = T) %>%
  collapse_rows(columns = c(1,13:14))
```

### Dados categóricos

```{r}
# Teste de hipóteses para dados categóricos
hipo_categorica <- function(dados, grupo, variavel){
  
  dados <- dados %>% drop_na(grupo) %>% mutate(grupo = ifelse(grupo == "0", "MN", "MP")) 
  data_grupo <- dados %>% dplyr::select( !!sym(grupo) ) %>% pull( !!sym(grupo) )
  data_variavel <- dados %>% dplyr::select( !!sym(variavel) ) %>% pull( !!sym(variavel) )
  tab = xtabs(~ data_variavel + data_grupo) # tabela de frequencia
  teste <- stats::chisq.test(tab, simulate.p.value = TRUE,  B = 10000)
  
  tabela <- list(
    `Variável` = variavel,
    Categorias = rownames(tab),
    MN = tab[,"MN"],
    `MN(%)` = paste0( (tab[,"MN"]/sum(tab[,"MN"]) * 100) %>% round(2) ,"%" ),
    MP = tab[,"MP"],
    `MP(%)` = paste0( (tab[,"MP"]/sum(tab[,"MP"]) * 100) %>% round(2) ,"%" ),
    `P(Teste)` = teste$p.value
    ) %>% as_tibble()
   
  return(tabela)
  }
```


```{r aplicando_teste_categoricos}
### Etnia:
variavel <- "etnia"
teste <- hipo_categorica(df_cat, "grupo", variavel)
tabela_resumo_cat <- teste

todas_variaveis <- names(df_cat)[-c(1,2)]

todas_variaveis <- todas_variaveis[-2] # tirando doenca por enquanto

for(variavel in todas_variaveis){
  teste <- hipo_categorica(df_cat, "grupo", variavel)
  tabela_resumo_cat <- rbind(tabela_resumo_cat, teste)
}

kbl(
  tabela_resumo_cat %>% arrange(`P(Teste)`), 
  digits = 3,
  format.args = list(decimal.mark = ',', big.mark = ".") 
  ) %>%
  kable_paper(full_width = F) %>%
  column_spec(1, bold = T) %>%
  collapse_rows(columns = c(1,7))
```

# Outras Informações

* Sobre Hipertensão e Usar anti hipertensivos

```{r}
Hipertensao <- df_completo$hipertensao  %>% as.factor(); AntiHiper <- df_completo$anti_hiper %>% as.factor()
tab <- xtabs(~  Hipertensao + AntiHiper)
tab

# df_completo %>% group_by(hipertensao, anti_hiper) %>% summarise(N = n()) %>% pivot_wider(names_from = anti_hiper, names_prefix = "anti_hiper_", values_from = N)

teste <- stats::chisq.test(tab, simulate.p.value = TRUE,  B = 10000) # df deu NA, estranho

library(patchwork)
g1 <- ggplot(data = df_completo) +
  geom_boxplot(aes(x = as.factor(hipertensao), y = pressao_media))

g2 <- ggplot(data = df_completo) +
  geom_boxplot(aes(x = as.factor(anti_hiper), y = pressao_media))

g1 + g2
```

```{r}
cat_sig <- c("gpsanguineo", 
              "elitista",
              "anti_hiper",
              "hipertensao",
              "escolaridade",
              "escolaridade_bin")
```

* Correlações:

```{r}
data <- df_num %>% drop_na() %>% select(-grupo)

num_sig <- tabela_resumo %>% filter(`P(Manh-W)` < 0.1 | `P(Test-T)` < 0.1) %>% pull("Variável") %>% unique()
data_sig <- data %>% select(all_of(num_sig))

corrplot::corrplot(cor(data_sig) %>% round(3),
                   diag = F, type = "upper", order="hclust"
                   )

## Tirando correlacionadas
num_sig_sem_corr <- c(
  "imc", "pressao_media", "ldl_dosado", "colesterol_total", "filtr_glomerular", "triglicerides")

data_sig_sem_corr <- data %>% select(all_of(num_sig_sem_corr))
corrplot::corrplot(cor(data_sig_sem_corr), 
                   method = "color", diag = F, type = "upper",addCoef.col = "black", order="hclust"
                   )
```

* Teste de MLG pra grupo

```{r}
# Modelo 1
teste <- glm(
  formula = grupo ~ imc  + pressao_media, 
  family = binomial(link = "logit"), data = df_completo %>% drop_na(imc))
teste %>% summary()
100 * (exp( coef(teste)[-1]) - 1)


df_completo <- df_completo %>% mutate(imc_estrato = ifelse(imc < 25, "normal", "alterado"))
teste <- glm(
  formula = grupo ~ imc_estrato  + pressao_media, 
  family = binomial(link = "logit"), data = df_completo %>% drop_na(imc))
teste %>% summary()
100 * (exp( coef(teste)[-1]) - 1)

teste <- glm(
  formula = grupo ~ imc  + pressao_media + filtr_glomerular, 
  family = binomial(link = "logit"), data = df_completo %>% drop_na(imc))
teste %>% summary()
100 * (exp( coef(teste)[-1]) - 1)

teste <- glm(
  formula = grupo ~ imc_estrato  + pressao_media  + filtr_glomerular, 
  family = binomial(link = "logit"), data = df_completo %>% drop_na(imc))
teste %>% summary()
100 * (exp( coef(teste)[-1]) - 1)


teste <- glm(
  formula = grupo ~ imc_estrato  + pressao_media  + filtr_glomerular + ldl_dosado, 
  family = binomial(link = "logit"), data = df_completo %>% drop_na(imc))
teste %>% summary()
100 * (exp( coef(teste)[-1]) - 1)
```

* Teste de LM pra variaveis numéricas

```{r}
#num_sig_sem_corr # variaveis numericas pra reg

## LDL
fit1 <- lm(ldl_dosado ~ imc + pressao_media + colesterol_total + filtr_glomerular + triglicerides, df_num)
summary(fit1)
fit_final<- update(fit1, ~ pressao_media + colesterol_total)
summary(fit_final)
reglin::ggresiduals(fit_final)

## IMC
fit1 <- lm(imc ~ pressao_media + colesterol_total + filtr_glomerular + triglicerides, df_num)
summary(fit1)
fit_final<- update(fit1, ~ pressao_media + filtr_glomerular + triglicerides)
summary(fit_final)
reglin::ggresiduals(fit_final)

## Colesterol
fit1 <- lm(colesterol_total ~ ldl_dosado + imc + pressao_media + filtr_glomerular + triglicerides, df_num)
summary(fit1)
fit_final<- update(fit1, ~ . -pressao_media -filtr_glomerular)
summary(fit_final)
reglin::ggresiduals(fit_final)
```

```{r}
df_num_numeric <- df_num[, sapply(df_num, is.numeric)]

variaveis_interesse <- c("imc", "pressao_media", "colesterol_total")

correlacoes <- cor(df_num_numeric[, variaveis_interesse], df_num_numeric[, setdiff(names(df_num_numeric), variaveis_interesse)], use = "pairwise.complete.obs")

# Obter índices das correlações maiores que 0.5
indices_maior_que_05 <- which(abs(correlacoes) > 0.5, arr.ind = TRUE)

# Obter os nomes das variáveis correspondentes
variaveis_correlacionadas <- rownames(correlacoes)[indices_maior_que_05[, 1]]
variaveis_correlacionadas_com <- colnames(correlacoes)[indices_maior_que_05[, 2]]

# Criar um data frame com os pares de variáveis correlacionadas
pares_correlacionados <- data.frame(
  Variavel1 = variaveis_correlacionadas,
  Variavel2 = variaveis_correlacionadas_com,
  Correlacao = correlacoes[indices_maior_que_05]
)

pares_correlacionados
```

```{r}
escolaridade_bin<- ifelse(df_cat$escolaridade_bin == "superior", 1, 0)
binarias<- c("grupo","medic_diabetes","medic_hipercol","tabagista","elitista",
             "anti_hiper","hipertensao","diabetes","hipercolesterolemia","sangueo", "escolaridade_bin")

maisdeduascategorias<- c("etnia","escolaridade","num_gestacoes","categoriaimc")
imc<- df_num$imc
pressao_media<- df_num$pressao_media
colesterol_total<- df_num$colesterol_total


# Lista para armazenar os p-valores
p_valores_imc <- numeric()
p_valores_pressao_media <- numeric()
p_valores_colesterol_total <- numeric()

# Loop sobre as variáveis binárias
for (var_binaria in binarias) {
  grupo1_imc <- imc[df_cat[[var_binaria]] == 0]
  grupo2_imc <- imc[df_cat[[var_binaria]] == 1]
  
  grupo1_pressao_media <- pressao_media[df_cat[[var_binaria]] == 0]
  grupo2_pressao_media <- pressao_media[df_cat[[var_binaria]] == 1]
  
  grupo1_colesterol_total <- colesterol_total[df_cat[[var_binaria]] == 0]
  grupo2_colesterol_total <- colesterol_total[df_cat[[var_binaria]] == 1]
  
  # Verificar se há dados suficientes para realizar o teste t para imc
  if (length(grupo1_imc) >= 3 & length(grupo2_imc) >= 3) {
    # Teste t de Student para imc
    resultado_t_test_imc <- t.test(grupo1_imc, grupo2_imc)
    
    # Armazenar o p-valor
    p_valores_imc <- c(p_valores_imc, resultado_t_test_imc$p.value)
  } else {
    p_valores_imc <- c(p_valores_imc, NA)
  }
  
  # Verificar se há dados suficientes para realizar o teste t para pressao_media
  if (length(grupo1_pressao_media) >= 3 & length(grupo2_pressao_media) >= 3) {
    # Teste t de Student para pressao_media
    resultado_t_test_pressao_media <- t.test(grupo1_pressao_media, grupo2_pressao_media)
    
    # Armazenar o p-valor
    p_valores_pressao_media <- c(p_valores_pressao_media, resultado_t_test_pressao_media$p.value)
  } else {
    p_valores_pressao_media <- c(p_valores_pressao_media, NA)
  }
  
  # Verificar se há dados suficientes para realizar o teste t para colesterol_total
  if (length(grupo1_colesterol_total) >= 3 & length(grupo2_colesterol_total) >= 3) {
    # Teste t de Student para colesterol_total
    resultado_t_test_colesterol_total <- t.test(grupo1_colesterol_total, grupo2_colesterol_total)
    
    # Armazenar o p-valor
    p_valores_colesterol_total <- c(p_valores_colesterol_total, resultado_t_test_colesterol_total$p.value)
  } else {
    p_valores_colesterol_total <- c(p_valores_colesterol_total, NA)
  }
}

# Criar um data frame com os p-valores
resultados_p_valores <- data.frame(Variavel = binarias, P_valor_IMC = p_valores_imc, P_valor_Pressao_Media = p_valores_pressao_media, P_valor_Colesterol_Total = p_valores_colesterol_total)

# Visualizar os resultados
print(resultados_p_valores)

```

```{r}
maisdeduascategorias<- c("etnia","escolaridade","num_gestacoes","categoriaimc")

df_cat$etnia<- as.factor(df_cat$etnia)
df_cat$escolaridade<- as.factor(df_cat$escolaridade)
df_cat$num_gestacoes<- as.factor(df_cat$num_gestacoes)
df_cat$categoriaimc<- as.factor(df_cat$categoriaimc)

# Lista para armazenar os resultados do teste de Kruskal-Wallis
resultados_kw <- list()

# Variáveis numéricas
numericas <- c("imc", "pressao_media", "colesterol_total")

# Loop sobre as variáveis numéricas
for (numerica in numericas) {
  # Vetores para armazenar os resultados
  categorias <- maisdeduascategorias
  p_valores <- numeric(length(categorias))
  
  # Loop sobre as variáveis categóricas com mais de duas categorias
  for (i in seq_along(categorias)) {
    # Verificar se há dados suficientes em cada grupo
    if (all(table(df_cat[[categorias[i]]]) >= 3)) {
      # Teste de Kruskal-Wallis
      resultado_kw <- kruskal.test(df_num[[numerica]] ~ df_cat[[categorias[i]]])
      
      # Armazenar o p-valor
      p_valores[i] <- resultado_kw$p.value
    } else {
      cat(sprintf("Não foi possível realizar o teste de Kruskal-Wallis para %s e %s devido à falta de dados.\n", numerica, categorias[i]))
      p_valores[i] <- NA
    }
  }
  
  # Armazenar os resultados na lista
  resultados_kw[[numerica]] <- data.frame(Categoria = categorias, P_Valor = p_valores)
}

# Exibir os resultados
for (numerica in numericas) {
  cat(sprintf("=== Resultados para %s ===\n", numerica))
  print(resultados_kw[[numerica]])
}
```
